
version: 1.0.11.{build}
image: Visual Studio 2017
branches:
  except:
  - master
shallow_clone: true
build_script:
- cmd: >-
    dotnet build -c Release -o result UCloudSDK.NetCore2

    dotnet publish -c Release -o publish UCloudSDK.NetCore2
artifacts:
- path: UCloudSDK.NetCore2\publish
  name: UCloudSDK.NetCore2-$(APPVEYOR_BUILD_VERSION)
  type: WebDeployPackage
- path: '**\*.nupkg'
deploy:
- provider: GitHub
  auth_token:
    secure: VFLWVehXTfNaqBsG5F8ZkEWTFKvDxhk71wQJ+ZDspUEoqfvXpbQwkB0OA/N+r/qD
  draft: false
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key:
    secure: Rqf5risUJkZAEiDPi/1c30DZ5dpcJ/XYOyd4ujH15av4x8t78ZYsl/D9SLH1Jgy2
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true